# Generated by Django 3.2.9 on 2022-03-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('winter', 'winter'), ('all season', 'all season'), ('summer', 'summer')], max_length=200, null=True),
        ),
    ]
