# Generated by Django 3.2.9 on 2022-03-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220311_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user',
            new_name='name',
        ),
    ]
