# Generated by Django 3.2.9 on 2022-03-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
    ]
