# Generated by Django 3.2.9 on 2022-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220311_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
