# Generated by Django 3.2.9 on 2022-03-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_owner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='username',
            new_name='user',
        ),
    ]
