# Generated by Django 3.2.9 on 2022-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_username_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='resource_km',
        ),
        migrations.RemoveField(
            model_name='component',
            name='resource_time',
        ),
        migrations.AddField(
            model_name='component',
            name='resource',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='unit',
            field=models.CharField(choices=[('1', 'km'), ('0', 'months')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.CharField(choices=[('winter', 'winter'), ('all season', 'all season'), ('summer', 'summer')], default='all season', max_length=200, null=True),
        ),
    ]
