# Generated by Django 3.2.9 on 2022-03-20 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220320_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='date_created',
        ),
        migrations.AddField(
            model_name='component',
            name='date_installation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='unit',
            field=models.CharField(choices=[('Km', 'km'), ('Months', 'months')], max_length=200, null=True),
        ),
    ]
