# Generated by Django 3.2.9 on 2022-03-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220320_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mileage_installation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
